// <auto-generated />
using ASPWebApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ASPWebApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260221040506_SeedUsersAdain")]
    partial class SeedUsersAdain
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ASPWebApp.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "User"
                        });
                });

            modelBuilder.Entity("ASPWebApp.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 3,
                            Email = "admin@gmail.com",
                            Name = "Super Admin",
                            Password = "AQAAAAEAACcQAAAAEEnE162OfCo1MXZom93FM/AfDyM7sFnruaIlJPcPuQPbapELOEaRpGl3rgU/KdxzQA==",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 4,
                            Email = "user1@gmail.com",
                            Name = "User 1",
                            Password = "AQAAAAIAAYagAAAAEJ+AWDdxL8AFYEWn7ZZWFITGkTzffI55U74QH2nn7rbJfnYMR9bQesyQkYCrLFbRgw==",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 5,
                            Email = "user2@gmail.com",
                            Name = "User 2",
                            Password = "AQAAAAIAAYagAAAAENSeevxiOZmmSfM5Un/M6XTxGuPyuF7+ItLA1pTGEy/o5czgSee1832Q19aIhignWg==",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 6,
                            Email = "user3@gmail.com",
                            Name = "User 3",
                            Password = "AQAAAAIAAYagAAAAEH1EyviE0aDWa0UbLIeJGlAFK2M1NvN4qGckrU8wiC/HrBiaFbJbb/9DJ//kMnBCFw==",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 7,
                            Email = "user4@gmail.com",
                            Name = "User 4",
                            Password = "AQAAAAIAAYagAAAAEMapLh3B1bpBSaiI0hhxsmaH7Hq5TZMojoJ8KTXrUp63xTmt1LXqp3mKcvA1CqtDuA==",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 8,
                            Email = "user5@gmail.com",
                            Name = "User 5",
                            Password = "AQAAAAIAAYagAAAAEDTmvDqI+a9T3jHd1+CzaRWOvF6Emdp9QqtGmLezP6yYWmuC8qg9xCeWHfwUEzB/1Q==",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 9,
                            Email = "user6@gmail.com",
                            Name = "User 6",
                            Password = "AQAAAAIAAYagAAAAEPhb42gLaX7ul5vudIcg5VZ60jzfKyM0y9APNzyirHHskCLdouU7kvSAGy2BPI0Jlg==",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 10,
                            Email = "user7@gmail.com",
                            Name = "User 7",
                            Password = "AQAAAAIAAYagAAAAEO7VT/PxsL+ZR34TkkbN6irS75Dn61dc3MTzn6wrS4te9+8PSTsiIAe0PH0+M6QHcw==",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 11,
                            Email = "user8@gmail.com",
                            Name = "User 8",
                            Password = "AQAAAAIAAYagAAAAEGBzziwGgbObjvg1zOHFpdGMl+aWckIabQGrNgkEtFI65k5Bgvzcx6J39AFi3pP7Og==",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 12,
                            Email = "user9@gmail.com",
                            Name = "User 9",
                            Password = "AQAAAAIAAYagAAAAEKWCCbVzwDOqE9lOOpFqSZRTYOKiapEEh/9BxtZowYDtUXSpJQ0HDIaQ7k4p+mjEBQ==",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 13,
                            Email = "user10@gmail.com",
                            Name = "User 10",
                            Password = "AQAAAAIAAYagAAAAEN4uHuDTbZpPOjw8NFZ37Rtm5VG7/jPvuvC3VLZ8tiijgu1JyskvFb+7xSXSDJeWNg==",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 14,
                            Email = "user11@gmail.com",
                            Name = "User 11",
                            Password = "AQAAAAIAAYagAAAAEMqfDkqH4+T/W55wAA9NpcMEHGg6pNiPpLnLFioYEEHyvSLqxP0+zmXvN2NAMd/v1g==",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 15,
                            Email = "user12@gmail.com",
                            Name = "User 12",
                            Password = "AQAAAAIAAYagAAAAECVzapduQ0G+wmeAjMpS3+eHa0UrP6AszTL81o0eKGdXmcFMt7YyuE/c/gYZJZ9BEg==",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 16,
                            Email = "user13@gmail.com",
                            Name = "User 13",
                            Password = "AQAAAAIAAYagAAAAELZAtjZKYnurMkAdOx+i1pigZkC0lRHteqp97XvhHyI/Za+VE2xHTyQTHC47PRmDMg==",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 17,
                            Email = "user14@gmail.com",
                            Name = "User 14",
                            Password = "AQAAAAIAAYagAAAAEKlo6ZHI4qS1KjlAFp7Es4+QrtNslNwcveDS8xGDDahEeeWerFl1R2iZQKsiOY+QRw==",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 18,
                            Email = "user15@gmail.com",
                            Name = "User 15",
                            Password = "AQAAAAIAAYagAAAAEI/AO8ypcbXecR88xZT1hLHximerRkjZodlKu5o2WkYIZoSnvOQKv2QK+dR16fQ6Xg==",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 19,
                            Email = "user16@gmail.com",
                            Name = "User 16",
                            Password = "AQAAAAIAAYagAAAAEHU7SZdSA6ZUZTKbIPnCSVj6Rsf2znwbspQ2ouU/cs/9gYdfSbgdvmPgrvKXx3Og+A==",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 20,
                            Email = "user17@gmail.com",
                            Name = "User 17",
                            Password = "AQAAAAIAAYagAAAAEExWC2j1OAC6+kFUPYsSJHfT+JTSsOd02RfjP5Dz9ZWfeygerLYgokuD8E9W65cNLw==",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 21,
                            Email = "user18@gmail.com",
                            Name = "User 18",
                            Password = "AQAAAAIAAYagAAAAEGuO6k4oVGfjiwpLIGQlI+33OHY08Dv22pp0HcHokOSWTMmKlffd3pRt/mVCokLOow==",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 22,
                            Email = "user19@gmail.com",
                            Name = "User 19",
                            Password = "AQAAAAIAAYagAAAAEF9UH7uL5kS8p0Z0KznFoLIWD2mjDzmKY1A5ByDtL+PlzLtUCf6Au8G4xp/DymhFOg==",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 23,
                            Email = "user20@gmail.com",
                            Name = "User 20",
                            Password = "AQAAAAIAAYagAAAAEE/I93M07+nJLlrvj5lf3FKXDwAWnfDoUfcSe+BsbhUPeNGf9Vl721JkxUkfISSDuA==",
                            RoleId = 2
                        });
                });

            modelBuilder.Entity("ASPWebApp.Models.User", b =>
                {
                    b.HasOne("ASPWebApp.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ASPWebApp.Models.Role", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
