// <auto-generated />
using ASPWebApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ASPWebApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260221033646_AddExtraUsers")]
    partial class AddExtraUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ASPWebApp.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "User"
                        });
                });

            modelBuilder.Entity("ASPWebApp.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            Email = "user1@gmail.com",
                            Name = "User 1",
                            Password = "3e7c19576488862816f13b512cacf3e4ba97dd97243ea0bd6a2ad1642d86ba72",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 3,
                            Email = "user2@gmail.com",
                            Name = "User 2",
                            Password = "3e7c19576488862816f13b512cacf3e4ba97dd97243ea0bd6a2ad1642d86ba72",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 4,
                            Email = "user3@gmail.com",
                            Name = "User 3",
                            Password = "3e7c19576488862816f13b512cacf3e4ba97dd97243ea0bd6a2ad1642d86ba72",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 5,
                            Email = "user4@gmail.com",
                            Name = "User 4",
                            Password = "3e7c19576488862816f13b512cacf3e4ba97dd97243ea0bd6a2ad1642d86ba72",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 6,
                            Email = "user5@gmail.com",
                            Name = "User 5",
                            Password = "3e7c19576488862816f13b512cacf3e4ba97dd97243ea0bd6a2ad1642d86ba72",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 7,
                            Email = "user6@gmail.com",
                            Name = "User 6",
                            Password = "3e7c19576488862816f13b512cacf3e4ba97dd97243ea0bd6a2ad1642d86ba72",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 8,
                            Email = "user7@gmail.com",
                            Name = "User 7",
                            Password = "3e7c19576488862816f13b512cacf3e4ba97dd97243ea0bd6a2ad1642d86ba72",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 9,
                            Email = "user8@gmail.com",
                            Name = "User 8",
                            Password = "3e7c19576488862816f13b512cacf3e4ba97dd97243ea0bd6a2ad1642d86ba72",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 10,
                            Email = "user9@gmail.com",
                            Name = "User 9",
                            Password = "3e7c19576488862816f13b512cacf3e4ba97dd97243ea0bd6a2ad1642d86ba72",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 11,
                            Email = "user10@gmail.com",
                            Name = "User 10",
                            Password = "3e7c19576488862816f13b512cacf3e4ba97dd97243ea0bd6a2ad1642d86ba72",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 12,
                            Email = "user11@gmail.com",
                            Name = "User 11",
                            Password = "3e7c19576488862816f13b512cacf3e4ba97dd97243ea0bd6a2ad1642d86ba72",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 13,
                            Email = "user12@gmail.com",
                            Name = "User 12",
                            Password = "3e7c19576488862816f13b512cacf3e4ba97dd97243ea0bd6a2ad1642d86ba72",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 14,
                            Email = "user13@gmail.com",
                            Name = "User 13",
                            Password = "3e7c19576488862816f13b512cacf3e4ba97dd97243ea0bd6a2ad1642d86ba72",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 15,
                            Email = "user14@gmail.com",
                            Name = "User 14",
                            Password = "3e7c19576488862816f13b512cacf3e4ba97dd97243ea0bd6a2ad1642d86ba72",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 16,
                            Email = "user15@gmail.com",
                            Name = "User 15",
                            Password = "3e7c19576488862816f13b512cacf3e4ba97dd97243ea0bd6a2ad1642d86ba72",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 17,
                            Email = "user16@gmail.com",
                            Name = "User 16",
                            Password = "3e7c19576488862816f13b512cacf3e4ba97dd97243ea0bd6a2ad1642d86ba72",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 18,
                            Email = "user17@gmail.com",
                            Name = "User 17",
                            Password = "3e7c19576488862816f13b512cacf3e4ba97dd97243ea0bd6a2ad1642d86ba72",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 19,
                            Email = "user18@gmail.com",
                            Name = "User 18",
                            Password = "3e7c19576488862816f13b512cacf3e4ba97dd97243ea0bd6a2ad1642d86ba72",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 20,
                            Email = "user19@gmail.com",
                            Name = "User 19",
                            Password = "3e7c19576488862816f13b512cacf3e4ba97dd97243ea0bd6a2ad1642d86ba72",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 21,
                            Email = "user20@gmail.com",
                            Name = "User 20",
                            Password = "3e7c19576488862816f13b512cacf3e4ba97dd97243ea0bd6a2ad1642d86ba72",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 100,
                            Email = "admin@gmail.com",
                            Name = "Super Admin",
                            Password = "AQAAAAEAACcQAAAAEEnE162OfCo1MXZom93FM/AfDyM7sFnruaIlJPcPuQPbapELOEaRpGl3rgU/KdxzQA==",
                            RoleId = 1
                        });
                });

            modelBuilder.Entity("ASPWebApp.Models.User", b =>
                {
                    b.HasOne("ASPWebApp.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ASPWebApp.Models.Role", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
